version: '3.9'

services:

  # the api container
  api:
    container_name: api
    build:
      context: ./app
      dockerfile: Dockerfile
    image: justingav/projekt-api:latest
    ports:
      # ports being listened on
      - "4000:4000"
  # the web container
  #web:
  #  container_name: web
  #  image: justingav/projekt-web:latest
  #  build: ./app/static
  #  ports:
  #    - "8000:8000"
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - /home/upload/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
