version: '3.9'

services:

  # the api container
  api:
    container_name: api
    build:
      context: ./app
      dockerfile: Dockerfile
    image: justingav/d0020e:latest
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      # ports being listened on
      - "4000:4000"
  db:
    container_name: db
    image: postgres:latest
    #volumes:
    #  - /home/upload/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #===== Development services =====
  api-test-runner:
    build:
      context: ./api-test-runner
      dockerfile: Dockerfile
    volumes:
      - ./api-test-runner:/app
    depends_on:
      - db

volumes:
  postgres_data: {}
