# This is a basic workflow to help you get started with Actions

name: API Test

# Define in which situiations and on what branches the workflow should be ran.
on:
  push:
    branches:
     - "*"
  pull_request:
    branches:
      - "*"

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Build the docker image
      - name: Build Docker images
        run: docker-compose up --build -d api db

      # Run the python test script in an isolated docker container
      - name: Run API tests
        run: docker-compose up api_test_runner
      #  run: docker-compose run --rm api_test_runner python -m unittest api_test
         


# == bug tracking code ==
#- name: List directory contents
#run: ls -l     
#- name: List api_test_runner directory contents
#  run: ls -l api_test_runner